# Generated by Django 5.2.11 on 2026-04-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool_Sharers_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('AC', 'Active'), ('RE', 'Returned'), ('CA', 'Cancelled'), ('DE', 'Declined')], default='PE', max_length=2),
        ),
    ]
