# Generated by Django 5.2.11 on 2026-04-01 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool_Sharers_App', '0002_user_reputation_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('FR', 'Fair'), ('WU', 'Well-Used')], default='GD', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tool_Sharers_App.category'),
        ),
    ]
