# Generated by Django 5.2.11 on 2026-04-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool_Sharers_App', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_payment',
            field=models.CharField(choices=[('VE', 'Venmo'), ('PP', 'PayPal'), ('NO', 'None')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='venmo_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
