# Generated by Django 6.0.2 on 2026-04-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tool_Sharers_App', '0005_geocodedaddress'),
        ('Tool_Sharers_App', '0005_message'),
    ]

    operations = [
    ]
