# Generated by Django 6.0.3 on 2026-04-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool_Sharers_App', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_sent',
            field=models.BooleanField(default=False),
        ),
    ]
