# Generated by Django 6.0.2 on 2026-04-21 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool_Sharers_App', '0008_transaction_payment_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tool_Sharers_App.listing'),
        ),
    ]
